language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script: npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
after_success: npm run coverage:report
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - GK_LOCK_COMMIT_AMEND=true
